#!/usr/bin/env bash
# Local dev playground for edge-guardian on macOS/Linux.
#
# Runs the daemon in DRY-RUN mode (no real firewall changes — nftables is Linux-only;
# on macOS the enforcer is a stub). Everything else is real: log tailing, scanner
# detection, allowlist, sliding-window threshold, state persistence, the control
# socket + `unban`, and the full web dashboard with live feed + Sentinel line.
#
# Usage:
#   bash dev/demo.sh            # build, configure, run (Ctrl-C to stop)
# Then open the dashboard URL it prints and, in another terminal:
#   bash dev/attack.sh          # inject simulated scanner hits
#   ./dist/edge-guardian -c dev/run/config.toml unban <ip>   # unban via control socket
set -euo pipefail

cd "$(dirname "$0")/.."

RUN=dev/run
PASS="edge-guardian"
PORT="${EG_PORT:-8787}"
LOG="$RUN/access.log"
AUTHLOG="$RUN/auth.log"
SOCK="$RUN/ns.sock"
CFG="$RUN/config.toml"

echo "==> Building edge-guardian (native, with dashboard assets)…"
make build VERSION=demo >/dev/null

# Seed the dashboard with a realistic spread across all detector types (demo-only).
export EG_DEMO_SEED=1

mkdir -p "$RUN"
: > "$LOG"
: > "$AUTHLOG"
rm -f "$SOCK" "$RUN/state.json"

echo "==> Generating bcrypt hash for the dashboard password…"
HASH="$(./dist/edge-guardian hash-password "$PASS")"

cat > "$CFG" <<EOF
# Auto-generated by dev/demo.sh — local playground, DRY-RUN (no real bans).
[log]
paths = ["$PWD/$LOG"]

[detection]
bad_uri_patterns = [
  '\.(php|cgi|asp|aspx|jsp|env|git|sql|bak)(\?|/|$)',
  '/(wp-admin|wp-login|wp-content|xmlrpc)',
  '/(phpmyadmin|pma|adminer)',
  '/(\.env|\.git|\.aws|\.ssh)',
]
threshold = 1
window_secs = 60
dry_run = true        # <-- detect + notify + dashboard, but DO NOT touch nftables

[ban]
duration = "24h"
whitelist = ["127.0.0.0/8", "::1/128", "10.0.0.0/8", "192.168.0.0/16"]
nft_table = "edge_guardian"
nft_set_v4 = "blocklist4"
nft_set_v6 = "blocklist6"

[telegram]
enabled = false

[geoip]
# Optional: export EG_GEOIP_CITY / EG_GEOIP_ASN (comma-separated .mmdb paths, e.g.
# free sapics/ip-location-db files) to see real country/ASN on real http+sshd bans.
city_db = "${EG_GEOIP_CITY:-}"
asn_db = "${EG_GEOIP_ASN:-}"

[exploit]
# Real exploit-signature detection (SQLi/traversal/RCE/Log4Shell) on the same access
# log (dev/attack.sh feeds it). Off by default in production; on here to demo it.
enabled = true
threshold = 1        # demo: ban on the first probe so the dashboard lights up at once
window_secs = 60

[badbot]
# Real bad-bot detection by User-Agent (sqlmap/nikto/nuclei/masscan… and automation
# libraries). Off by default in production; on here. Needs the (?P<ua>...) group in the
# default line_regex, which is present.
enabled = true
threshold = 1
window_secs = 60

[ratelimit]
# Real rate-abuse / DoS-lite detection: count every request per IP, ban a flood.
# Off by default in production (highest false-positive risk — allowlist your proxies/CDN).
# Demo threshold is tiny so a burst from one IP trips it.
enabled = true
threshold = 8
window_secs = 10

[sshd]
# Real SSH brute-force detection from a demo auth.log (dev/attack.sh feeds it).
enabled = true
paths = ["$PWD/$AUTHLOG"]
threshold = 3
window_secs = 60

[health]
# Edge health monitoring: same access log, aggregates per-site status/error-rate/latency
# and alerts on degraded/down. Demo data is seeded (EG_DEMO_SEED=1) so /sites is populated.
enabled = true
window_mins = 180
err_ratio_pct = 5
latency_p95_ms = 2000
sustained_mins = 5
cooldown_mins = 30

[state]
path = "$PWD/$RUN/state.json"

[control]
enabled = true
socket_path = "$PWD/$SOCK"

[dashboard]
enabled = true
listen = "127.0.0.1:$PORT"
username = "admin"
password_hash = "$HASH"
EOF

URL="http://127.0.0.1:$PORT"
echo
echo "=================================================================="
echo " edge-guardian demo is starting (DRY-RUN — no firewall changes)"
echo "   Dashboard : $URL"
echo "   Login     : admin / $PASS"
echo "   Log file  : $LOG   (append scanner-looking requests here)"
echo "   Inject    : bash dev/attack.sh"
echo "   Unban     : ./dist/edge-guardian -c $CFG unban <ip>"
echo "   Stop      : Ctrl-C"
echo "=================================================================="
echo

# Seed a burst of simulated attacks ~2.5s after startup (daemon tails from end, so
# data must arrive AFTER it is listening) — so the dashboard isn't empty on first open.
( sleep 2.5; bash dev/attack.sh >/dev/null 2>&1 || true ) &

# Open the browser (macOS `open`, Linux `xdg-open`) — best effort, after seed.
( sleep 3.5; (command -v open >/dev/null && open "$URL") || (command -v xdg-open >/dev/null && xdg-open "$URL") ) >/dev/null 2>&1 &

exec ./dist/edge-guardian -c "$CFG"
